package definitivo;

import java.awt.Color;

/**
 *
 * @author Dulce
 */
public class Page1 extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
    public Page1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        adiosPanel = new javax.swing.JPanel();
        adiosLBL = new javax.swing.JLabel();
        ingresoDatoPanel = new javax.swing.JPanel();
        ingresoDatoLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(216, 255, 237));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 490, -1));

        adiosPanel.setBackground(new java.awt.Color(255, 255, 255));
        adiosPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        adiosLBL.setBackground(new java.awt.Color(255, 255, 255));
        adiosLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        adiosLBL.setForeground(new java.awt.Color(255, 0, 0));
        adiosLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adiosLBL.setText("ADIOS");
        adiosLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adiosLBLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adiosLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adiosLBLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout adiosPanelLayout = new javax.swing.GroupLayout(adiosPanel);
        adiosPanel.setLayout(adiosPanelLayout);
        adiosPanelLayout.setHorizontalGroup(
            adiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adiosLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        adiosPanelLayout.setVerticalGroup(
            adiosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adiosLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(adiosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, -1, -1));

        ingresoDatoPanel.setBackground(new java.awt.Color(255, 255, 255));

        ingresoDatoLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ingresoDatoLBL.setForeground(new java.awt.Color(0, 153, 153));
        ingresoDatoLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoDatoLBL.setText("INGRESAR DATOS");
        ingresoDatoLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoDatoLBLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresoDatoLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresoDatoLBLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresoDatoPanelLayout = new javax.swing.GroupLayout(ingresoDatoPanel);
        ingresoDatoPanel.setLayout(ingresoDatoPanelLayout);
        ingresoDatoPanelLayout.setHorizontalGroup(
            ingresoDatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoDatoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        ingresoDatoPanelLayout.setVerticalGroup(
            ingresoDatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresoDatoLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(ingresoDatoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 217, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, 180));
    }// </editor-fold>                        

    private void adiosLBLMouseClicked(java.awt.event.MouseEvent evt) {                                      
        System.exit(0);
    }                                     

    private void adiosLBLMouseEntered(java.awt.event.MouseEvent evt) {                                      
        adiosPanel.setBackground(Color.red);
        adiosLBL.setForeground(Color.black);
    }                                     

    private void adiosLBLMouseExited(java.awt.event.MouseEvent evt) {                                     
        adiosPanel.setBackground(Color.white);
        adiosLBL.setForeground(new Color(255, 0, 0));
    }                                    

    private void ingresoDatoLBLMouseClicked(java.awt.event.MouseEvent evt) {                                            
        Page2 p2 = new Page2();
        p2.setSize(543,290);
        p2.setLocation(0,0);
        
        Inicio inicio = new Inicio();
        inicio.modificarJPanel(p2);
    }                                           

    private void ingresoDatoLBLMouseEntered(java.awt.event.MouseEvent evt) {                                            
        ingresoDatoPanel.setBackground(new Color(0, 204, 204));
        ingresoDatoLBL.setForeground(Color.black);
    }                                           

    private void ingresoDatoLBLMouseExited(java.awt.event.MouseEvent evt) {                                           
        ingresoDatoPanel.setBackground(Color.white);
        ingresoDatoLBL.setForeground(new Color(0, 204, 204));
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JLabel adiosLBL;
    private javax.swing.JPanel adiosPanel;
    private javax.swing.JLabel ingresoDatoLBL;
    private javax.swing.JPanel ingresoDatoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration                   
}
