package definitivo;

import java.awt.Color;

/**
 *
 * @author Dulce
 */
public class Page2 extends javax.swing.JPanel {

    /**
     * Creates new form Page2
     */
    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ver = new javax.swing.JPanel();
        verLBL = new javax.swing.JLabel();
        regresarPanel = new javax.swing.JPanel();
        regresarLBL = new javax.swing.JLabel();
        datosPanel = new javax.swing.JPanel();
        datosLBL = new javax.swing.JLabel();
        insertarPanel = new javax.swing.JPanel();
        insertarLBL = new javax.swing.JLabel();
        campoLBL = new javax.swing.JLabel();
        Campostxt = new javax.swing.JTextField();
        CamposLBL1 = new javax.swing.JLabel();
        Campostxt1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(216, 255, 237));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        ver.setBackground(new java.awt.Color(255, 255, 255));

        verLBL.setBackground(new java.awt.Color(0, 153, 0));
        verLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        verLBL.setForeground(new java.awt.Color(0, 153, 0));
        verLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verLBL.setText("VER");
        verLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verLBLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verLBLMousePressed(evt);
            }
        });

        javax.swing.GroupLayout verLayout = new javax.swing.GroupLayout(ver);
        ver.setLayout(verLayout);
        verLayout.setHorizontalGroup(
            verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        verLayout.setVerticalGroup(
            verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        regresarPanel.setBackground(new java.awt.Color(255, 255, 255));
        regresarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresarPanelMouseEntered(evt);
            }
        });

        regresarLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        regresarLBL.setForeground(new java.awt.Color(255, 0, 0));
        regresarLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresarLBL.setText("REGRESAR");
        regresarLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresarLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarLBLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresarLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresarLBLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout regresarPanelLayout = new javax.swing.GroupLayout(regresarPanel);
        regresarPanel.setLayout(regresarPanelLayout);
        regresarPanelLayout.setHorizontalGroup(
            regresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regresarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresarLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        regresarPanelLayout.setVerticalGroup(
            regresarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regresarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresarLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        datosPanel.setBackground(new java.awt.Color(255, 255, 255));

        datosLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        datosLBL.setForeground(new java.awt.Color(200, 167, 36));
        datosLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosLBL.setText("A. DATOS");
        datosLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datosLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datosLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datosLBLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                datosLBLMousePressed(evt);
            }
        });

        javax.swing.GroupLayout datosPanelLayout = new javax.swing.GroupLayout(datosPanel);
        datosPanel.setLayout(datosPanelLayout);
        datosPanelLayout.setHorizontalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(datosLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        datosPanelLayout.setVerticalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(datosLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        insertarPanel.setBackground(new java.awt.Color(255, 255, 255));

        insertarLBL.setBackground(new java.awt.Color(250, 250, 250));
        insertarLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        insertarLBL.setForeground(new java.awt.Color(51, 51, 255));
        insertarLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertarLBL.setText("INSERTAR");
        insertarLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertarLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertarLBLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertarLBLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout insertarPanelLayout = new javax.swing.GroupLayout(insertarPanel);
        insertarPanel.setLayout(insertarPanelLayout);
        insertarPanelLayout.setHorizontalGroup(
            insertarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insertarLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        insertarPanelLayout.setVerticalGroup(
            insertarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insertarLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        campoLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        campoLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoLBL.setText("Ingrese un dato:   ");

        Campostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampostxtActionPerformed(evt);
            }
        });

        CamposLBL1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CamposLBL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CamposLBL1.setText("Ingrese la cantidad de datos a tratar:");

        Campostxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campostxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CamposLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Campostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(campoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Campostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(regresarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(insertarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CamposLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void verLBLMouseEntered(java.awt.event.MouseEvent evt) {                                    
        ver.setBackground(new Color(153,255,153));
        verLBL.setForeground(Color.black);
    }                                   

    private void verLBLMouseExited(java.awt.event.MouseEvent evt) {                                   
        ver.setBackground(Color.white);
        verLBL.setForeground(new Color(0,153,0));
    }                                  

    private void verLBLMousePressed(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void regresarLBLMouseClicked(java.awt.event.MouseEvent evt) {                                         
        //
    }                                        

    private void regresarLBLMouseEntered(java.awt.event.MouseEvent evt) {                                         
        regresarPanel.setBackground(new Color(248,105,105));
        regresarLBL.setForeground(Color.black);
    }                                        

    private void regresarLBLMouseExited(java.awt.event.MouseEvent evt) {                                        
        regresarPanel.setBackground(Color.white);
        regresarLBL.setForeground(new Color(255,0,0));
    }                                       

    private void regresarPanelMouseEntered(java.awt.event.MouseEvent evt) {                                           

    }                                          

    private void datosLBLMouseEntered(java.awt.event.MouseEvent evt) {                                      
        datosPanel.setBackground(new Color(255,255,153));
        datosLBL.setForeground(Color.black);
    }                                     

    private void datosLBLMouseExited(java.awt.event.MouseEvent evt) {                                     
        datosPanel.setBackground(Color.white);
        datosLBL.setForeground(new Color(200,167,36));
    }                                    

    private void datosLBLMousePressed(java.awt.event.MouseEvent evt) {                                      

    }                                     

    private void insertarLBLMouseEntered(java.awt.event.MouseEvent evt) {                                         
        insertarPanel.setBackground(new Color(153,153,255));
        insertarLBL.setForeground(Color.BLACK);
    }                                        

    private void insertarLBLMouseExited(java.awt.event.MouseEvent evt) {                                        
        insertarPanel.setBackground(Color.white);
        insertarLBL.setForeground(new Color(51,51,255));
    }                                       

    private void CampostxtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Campostxt1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                         
    
    public static void main(String[] args) {
        Page2 p2 = new Page2();
    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel CamposLBL1;
    private javax.swing.JTextField Campostxt;
    private javax.swing.JTextField Campostxt1;
    private javax.swing.JLabel campoLBL;
    private javax.swing.JLabel datosLBL;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JLabel insertarLBL;
    private javax.swing.JPanel insertarPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel regresarLBL;
    private javax.swing.JPanel regresarPanel;
    private javax.swing.JPanel ver;
    private javax.swing.JLabel verLBL;
    // End of variables declaration                   
}
