package Pruebas;

import java.awt.BorderLayout;
import java.awt.Component;
import mx.unam.ig.a.Page1;
import mx.unam.ig.a.Page2;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;

public class Inicio extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public void modificarJPanel(Object ob){
        content.removeAll();
        content.add((Component) ob, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    public void botones4Vis(boolean bln){
        regresarBTN.setVisible(bln);
        agregarDatoBTN.setVisible(bln);
        insertarBTN.setVisible(bln);
        verBTN.setVisible(bln);
    }
    
    public void botones2Vis(boolean bln){
        adiosBTN.setVisible(bln);
        ingresoDato.setVisible(bln);
    }
    
    public Inicio() {
        initComponents();
        
        Page1 p1 = new Page1();
        p1.setSize(543,290);
        p1.setLocation(0,0);
        
        this.modificarJPanel(p1);
        this.botones4Vis(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        Timer relojTimer = new Timer(1000, new RelojListener());
        relojTimer.start();
        fecha = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        barra = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        verBTN = new javax.swing.JButton();
        adiosBTN = new javax.swing.JButton();
        insertarBTN = new javax.swing.JButton();
        regresarBTN = new javax.swing.JButton();
        ingresoDato = new javax.swing.JButton();
        agregarDatoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(216, 255, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Medium", 0, 22)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Estructura de datos");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        hora.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        hora.setText("00:00:00 MM");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fecha.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        fecha.setText(new definitivo.Inicio.Fecha().toString());
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 10));

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 490, 20));

        content.setBackground(new java.awt.Color(216, 255, 237));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(490, 258));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 490, 220));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 490, -1));

        verBTN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        verBTN.setForeground(new java.awt.Color(0, 153, 0));
        verBTN.setText("VER");
        verBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verBTNMouseExited(evt);
            }
        });
        verBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBTNActionPerformed(evt);
            }
        });
        jPanel1.add(verBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 30));

        adiosBTN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        adiosBTN.setForeground(new java.awt.Color(255, 0, 0));
        adiosBTN.setText("ADIOS");
        adiosBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adiosBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adiosBTNMouseExited(evt);
            }
        });
        adiosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiosBTNActionPerformed(evt);
            }
        });
        jPanel1.add(adiosBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        insertarBTN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        insertarBTN.setForeground(new java.awt.Color(51, 51, 255));
        insertarBTN.setText("INSERTAR");
        insertarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertarBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertarBTNMouseExited(evt);
            }
        });
        insertarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(insertarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));

        regresarBTN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        regresarBTN.setForeground(new java.awt.Color(255, 0, 0));
        regresarBTN.setText("REGRESAR");
        regresarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresarBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresarBTNMouseExited(evt);
            }
        });
        regresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(regresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        ingresoDato.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ingresoDato.setForeground(new java.awt.Color(0, 153, 255));
        ingresoDato.setText("INGRESAR DATOS");
        ingresoDato.setActionCommand("");
        ingresoDato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresoDatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresoDatoMouseExited(evt);
            }
        });
        ingresoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDatoActionPerformed(evt);
            }
        });
        jPanel1.add(ingresoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        agregarDatoBTN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        agregarDatoBTN.setForeground(new java.awt.Color(200, 167, 36));
        agregarDatoBTN.setText("A. DATOS");
        agregarDatoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarDatoBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarDatoBTNMouseExited(evt);
            }
        });
        agregarDatoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDatoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(agregarDatoBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                 

    private void formMouseDragged(java.awt.event.MouseEvent evt) {                                  
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }                                 

    private void ingresoDatoMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ingresoDato.setBackground(new Color(0, 204, 204));
        ingresoDato.setForeground(Color.black);
    }                                        

    private void ingresoDatoMouseExited(java.awt.event.MouseEvent evt) {                                        
        ingresoDato.setBackground(Color.white);
        ingresoDato.setForeground(new Color(0, 204, 204));
    }                                       

    private void ingresoDatoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Page2 p2 = new Page2();
        p2.setSize(543,290);
        p2.setLocation(0,0);
        
        this.modificarJPanel(p2);
        this.botones4Vis(true);
        this.botones2Vis(false);
    }                                           

    private void verBTNMouseEntered(java.awt.event.MouseEvent evt) {                                    
        verBTN.setBackground(new Color(153,255,153));
        verBTN.setForeground(Color.black);
    }                                   

    private void verBTNMouseExited(java.awt.event.MouseEvent evt) {                                   
        verBTN.setBackground(Color.white);
        verBTN.setForeground(new Color(0,153,0));
    }                                  

    private void verBTNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void adiosBTNMouseEntered(java.awt.event.MouseEvent evt) {                                      
        adiosBTN.setBackground(Color.red);
        adiosBTN.setForeground(Color.black);
    }                                     

    private void adiosBTNMouseExited(java.awt.event.MouseEvent evt) {                                     
        adiosBTN.setBackground(Color.white);
        adiosBTN.setForeground(new Color(255, 0, 0));
    }                                    

    private void adiosBTNActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);
    }                                        

    private void regresarBTNMouseEntered(java.awt.event.MouseEvent evt) {                                         
        regresarBTN.setBackground(new Color(248,105,105));
        regresarBTN.setForeground(Color.black);
    }                                        

    private void regresarBTNMouseExited(java.awt.event.MouseEvent evt) {                                        
        regresarBTN.setBackground(Color.white);
        regresarBTN.setForeground(new Color(255,0,0));
    }                                       

    private void regresarBTNActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Page1 p1 = new Page1();
        p1.setSize(543,290);
        p1.setLocation(0,0);
        
        this.modificarJPanel(p1);
        this.botones4Vis(false);
        this.botones2Vis(true);
    }                                           

    private void agregarDatoBTNMouseEntered(java.awt.event.MouseEvent evt) {                                            
        agregarDatoBTN.setBackground(new Color(255,255,153));
        agregarDatoBTN.setForeground(Color.black);
    }                                           

    private void agregarDatoBTNMouseExited(java.awt.event.MouseEvent evt) {                                           
        agregarDatoBTN.setBackground(Color.white);
        agregarDatoBTN.setForeground(new Color(200,167,36));
    }                                          

    private void agregarDatoBTNActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void insertarBTNMouseEntered(java.awt.event.MouseEvent evt) {                                         
        insertarBTN.setBackground(new Color(153,153,255));
        insertarBTN.setForeground(Color.BLACK);
    }                                        

    private void insertarBTNMouseExited(java.awt.event.MouseEvent evt) {                                        
        insertarBTN.setBackground(Color.white);
        insertarBTN.setForeground(new Color(51,51,255));
    }                                       

    private void insertarBTNActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    private class RelojListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss a");
            Date hora1 = new Date();
            hora1.setHours(hora1.getHours() - 1);
            hora.setText(sdf.format(hora1));
        }
    }
    public static class Fecha extends GregorianCalendar {
        private static String[] meses = {"Enero"
                , "Febrero"
                , "Marzo"
                , "Abril"
                , "Mayo"
                , "Junio"
                , "Julio"
                , "Agosto"
                , "Septiembre"
                , "Octubre"
                , "Noviembre"
                , "Diciembre"};

        @Override
        public String toString() {
            return Integer.toString(this.get(Calendar.DATE)) + "-" + meses[this.get(Calendar.MONTH)] + "-" + Integer.toString(this.get(Calendar.YEAR));
        }
    }
      

    // Variables declaration - do not modify                     
    private javax.swing.JButton adiosBTN;
    private javax.swing.JButton agregarDatoBTN;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JButton ingresoDato;
    private javax.swing.JButton insertarBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton regresarBTN;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton verBTN;
    // End of variables declaration                   
}
