package Pruebas;

public class Page2 extends javax.swing.JPanel {

    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        campoLBL = new javax.swing.JLabel();
        Campostxt = new javax.swing.JTextField();
        CamposLBL1 = new javax.swing.JLabel();
        Campostxt1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(216, 255, 237));
        setMinimumSize(new java.awt.Dimension(490, 258));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoLBL.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        campoLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoLBL.setText("Ingrese un dato:   ");
        add(campoLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, 120, 20));

        Campostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampostxtActionPerformed(evt);
            }
        });
        add(Campostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 47, 100, -1));

        CamposLBL1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        CamposLBL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CamposLBL1.setText("Ingrese la cantidad de datos a tratar:");
        add(CamposLBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 260, 20));

        Campostxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campostxt1ActionPerformed(evt);
            }
        });
        add(Campostxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 17, 60, -1));
    }// </editor-fold>                        

    private void CampostxtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Campostxt1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JLabel CamposLBL1;
    private javax.swing.JTextField Campostxt;
    private javax.swing.JTextField Campostxt1;
    private javax.swing.JLabel campoLBL;
    // End of variables declaration                   
}
